// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opsqiajdfgqmlssmnhbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wc3FpYWpkZmdxbWxzc21uaGJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjcxMzUsImV4cCI6MjA2MzQ0MzEzNX0.1TiUgVP7-WzQbbRyzBrRth4HkW83dniRn9-XolVzTh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);